### ISSUE TITLE
Bug + importazione libreria

### ISSUE THREAD

**Issue by Baque91** [MyAnimeManager/MyAnimeManager#2]
Salve. Intanto vi ringrazio per l'applicazione, decisamente utile e comoda per me che mi complicavo la vita ad archiviare tutto su un interminabile file Word, dopo aver abbandonato MyAnimeList e Animeclick causa connessione spesso poco fluida.

Avrei un problema da segnalare e una richiesta/proposta da fare.
Per quanto riguarda il bug: dopo l'installazione dell'ultimo aggiornamento, non riesco più ad aggiungere manualmente gli anime (se può essere utile per i futuri aggiornamenti dei vostri archivi, l'anime che cerco disperatamente e inutilmente di aggiungere è Wakaba*Girl, TV short andato in onda la scorsa estate).
Seconda cosa: a causa di alcuni aggiornamenti di Windows, mi sono ritrovato a dover reinstallare MyAnimeManager (o, semplicemente, a dover ricominciare daccapo l'archiviazione, ritrovandomi la libreria del programma completamente vuota). Avendo trovato comunque nelle AppData alcuni file .anaconda/txt, che presumo siano di backup (es. airing.anaconda, airing.txt, completed.anaconda, completed.txt, ecc.), mi chiedevo se fosse possibile importarli su MyAnimeManger in qualche modo oppure, in alternativa, renderlo fattibile con i prossimi aggiornamenti, così da semplificare la vita a chi, per i più svariati motivi, si ritrova a dover installare nuovamente il programma.

In attesa di risposta, vi ringrazio in anticipo.

**Comment by MyAnimeManager** [comment]
Ciao, per quanto riguarda la funzione di importo , per ora puoi mettere i file .anaconda vecchi dentro la cartella Anime che trovi dentro la cartella del programma in appdata, una volta aperto il programma dovresti trovare tutti gli anime che avevi inserito(ovviamente se quei file non sono vuoto). Per quanto riguarda il problema dell'aggiunta manuale, diamo un occhiata e ti sappiamo dire. Puoi nel frattempo vedere se dal menù preferenze hai la possibilità di esportare un file di log? Ti basta controllare se la dimensione è maggiore di 0, e in questo caso cliccare esporta. Se riesci a darci il file possiamo farci un'idea più chiara.

**Comment by Baque91** [comment]
Ok, problema libreria risolto.
Per quanto riguarda il file di Log, non mi permette di esportarlo (dimensione 0kb).
Intanto grazie mille!

**Comment by MyAnimeManager** [comment]
Il problema lo hai con l'aggiunta manuale o automatica?

**Comment by MyAnimeManager** [comment]
Chiudi per inattività
