### ISSUE TITLE
Bug Controllo Dati  e Inserimento Anime

### ISSUE THREAD

**Issue by FocusAndFire** [MyAnimeManager/MyAnimeManager#3]
Salve, e da ieri che sto avendo un problema di "Freeze e crash". Vi spiego semplicemente, quando attivo "Controllo dati automatici" mi si blocca tutto e non mi fa fare nulla, anche quando provo di entrare in "Opzioni" mi si blocca e dopo un po si sblocca (e quando riprovo a fare qualcosa si blocca nuovamente). Questo era il primo problema. 
Secondo problema, quando provo ad inserire un anime mi si blocca per un po, poi mi dice che l'anime che avevo cercato non c'era, ma in realtà già l'avevo messo dentro alla mia lista per controllare che era vero quello che mi diceva (ma in realtà non era così). Tutto qui, grazie in anticipo e del tutto lavoro svolto fin ora :D Buon lavoro.

**Comment by iTTou** [comment]
Salve FocusAndFire, il problema segnalato è causato dal fatto che il server di Anilist (che usa il programma per il controllo dati automatico e per l'inserimeto) e' offline. Purtroppo finchè non tornerà online il programma potrebbe continuare a presentare questo problema; consiglio pertanto di usare nel frattempo l'inserimento manuale e di disattivare il controllo dati automatico. 
Nella prossima versione aggiungeremo la gestione di casi come questo al fine di evitare il blocco totale del programma come si sta verificando ora. 
Nella speranza che il sever torni presto online, ti ringrazio per aver scaricato My Anime Manager e per averci fatto questa segnalazione.
Auguro un buon 2016!                                                                                                      

iTTo

**Comment by FocusAndFire** [comment]
Ti ringrazio moltissimo della tua risposta, e buon anno anche a tutti gli altri che lavorano per questa App. Buona anno :D
