### ISSUE TITLE
Problemi newboard+Problemi ricerca anime

### ISSUE THREAD

**Issue by Swarteagle** [MyAnimeManager/MyAnimeManager#4]
Salve,e da un 2 giorni che sto avendo problemi con la newboard(non mi spuntano più aggiornamenti delle ultime uscite ecc)e in più se provo ad aggiungere un qualsiasi anime alla lista tramite il tasto ''Aggiungi anime'' non me ne trova neanche uno(ho provato a ricercare anche quelli che gia ho ma niente).
Aspetto vostre notizie
Cordiali saluti

**Comment by MyAnimeManager** [comment]
Ciao, abbiamo entrambi provato e vanno sia l'aggiunta anime che la newsboard ad entrambi. Riesci a fornirci il file di log, che puoi esportare andando sulle impostazioni del programma, cliccando esporta sulla parte più in basso della finestra delle preferenze? Se la dimensione è 0kb significa che non ne hai, e dovremmo cercare un altro modo per capire il problema.

**Comment by Swarteagle** [comment]
[Uploading log_11_3_2016.txt…]()
[log_13_3_2016.txt](https://github.com/MyAnimeManager/MyAnimeManager/files/173135/log_13_3_2016.txt)

**Comment by MyAnimeManager** [comment]
Dal log a prima vista mi sembra un errore di permessi, che impedisce al programma di connettersi. Prova a vedere se disabilitando antivirus e firewall di Windows riesce a connettersi, se ancora non va prova anche ad eseguirlo come amministratore per sicurezza. Proverò comunque a vedere se è causato da qualcos'altro e nel caso ti so dire

**Comment by Swarteagle** [comment]
ti ringrazio dell'aiuto,appena ho 2 min liberi provo e ti faccio sapere.
Grazie ancora ;)

**Comment by Swarteagle** [comment]
allora ho provato per come mi hai detto,ma niente,ho dato tutti i permessi sia al firewall,disattivato l'antivirus,sono andato nelle propietà dell'app e da tutti i permessi possibili ed immaginabili ma niente.Posso dirti una cosa se può essere d'aiuto,prima di avere questi problemi il programma funzionava alla perfezione,ma ultimamente ho avuto problemi con delle pubblicità e quindi per risolvere il problema ho scaricato 4 programmi(di cui uno da installare e 3 erano eseguibili),dal momento in cui li ho usati le pubblicità sono scomparse ma il programma non andava più.Ora ho disinstallato l'unico programma(malwarebites)ma niente ho sempre problemi.Spero di esserti d'aiuto per questo problema.
Grazie ancora
P.s. ce un modo per non perdere tutti gli anime che ho memorizzato perché ho pensato di disinstallare il programma e reinstallarlo però non vorrei perdere ciò che ho già memorizzato.

**Comment by MyAnimeManager** [comment]
Ho controllato meglio l'errore, e sembra essere un problema di qualche certificato, probabilmente tolto erroneamente da qualcuno dei programmi di cui hai detto ( malwarebytes non credo, è un buon programma). Volendo se non va disintallando e reinstallando il programma puoi provare a fare lo stesso con Java, può essere che sia stato tolto qualche certificato. Per quanto riguarda le liste, per ora devi fare manualmente, ma la metteremo come funzione nella prossima versione: vai su esegui (o sulla barra di ricerca se hai win 10) e scrivi %appdata% e dai invio. Cerca la cartella MyAnimeManager, aprila e copiati la cartella Anime, images e fansub ( se hai modificato qualche impostazione anche properties) sul desktop. poi disinstalli e dopo aver reinstallato e fatto partire una volta il programma rimetti i file nella cartella, se ti chiede di sostituire fai si, e dovresti avere di nuovo tutte le liste

**Comment by Swarteagle** [comment]
Perfetto,ho fatto come mi hai detto disinstallato java e il programma e reinstallato tutto,ora tutto funziona alla perfezione,grazie ancora dell'aiuto 
Cordiali Saluti

**Comment by MyAnimeManager** [comment]
Di nulla, grazie a te per usare MAM ^^
