### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by raffybest94V01** [MyAnimeManager/MyAnimeManager#5]
salve, voglio segnalare che non fa trovare l'anime "Kobayashi-san Chi no Maid Dragon" anche se voglio aggiungerlo manualmente una volta che clicco salva non lo aggiunge, risolvete grazie.

**Comment by iTTou** [comment]
Nell'aggiunta mediante ricerca nel database di Anilist il problema è il carattere "-" se cerca il titolo scrivendo solo "kobayashi" o semplicemente sostituendo suddetto carattere con uno spazio bianco glielo troverà immediatamente.
Non riscontriamo invece alcun malfunzionamento con l'aggiunta manuale, se riesce a fornirci i file di log reperibili nel menù impostazioni faremo il possibile per risolvere il problema che le si presenta.
Ringraziandola per la segnalazione ci impegniamo a risolvere tali problemi con il prossimo aggiornamento. Saluti, 
TEAM MyAnimeManager

**Comment by raffybest94V01** [comment]
[log_19_8_2016.txt](https://github.com/MyAnimeManager/MyAnimeManager/files/715426/log_19_8_2016.txt)

grazie, per la soluzione del carattere, per quanto riguarda l'aggiunta manuale non va proprio, dovrei aver caricato correttamente il file log, spero che sia utile.

**Comment by raffybest94V01** [comment]
ho appena visto che posso selezionare anche un'altro file per l'esportazione, e questo è l'ultimo. 
[log_27_12_2016.txt](https://github.com/MyAnimeManager/MyAnimeManager/files/715429/log_27_12_2016.txt)

**Comment by MyAnimeManager** [comment]
Ho provato ad usare l'aggiunta manuale e non mi crea nessun problema e viene aggiunto correttamente. Sei sicuro di non avere la spunta su "Non Chiudere" nella tab Aggiunta automatica ? In quel caso l'anime viene aggiunto ma la finestra non si chiude.

**Comment by raffybest94V01** [comment]
ti faccio direttamente il video, la spunta "Non chiudere" non c'è nemmeno a me, la versione è l'ultima sia per MAM che del JAVA, ma nonostante tutto c'è anche un bug strano che posso risolvere riavviando il programma, ovvero mentre col cursore navigo nel programma alcune parti diventano tutte bianche, e quello lo risolvo riavviando, ma comunque quello più importante e che ora non mi fa aggiungere gli anime manualmente. 

[prova video.zip](https://github.com/MyAnimeManager/MyAnimeManager/files/717543/prova.video.zip)

**Comment by MyAnimeManager** [comment]
Ho visto il video e ti manca per esempio la lista dei fansub, e presumo sia quello il motivo per cui non ti fa aggiungere gli anime. Ti consiglio di esportare le liste tramite la funzione apposita nelle opzioni del programma e reinstallare il programma, data la mancanza di alcuni file.

**Comment by raffybest94V01** [comment]
disinstallato ( esportando ovviamente la mia lista ) reistallato e nulla, non riesco ad aggiungere un'anime manualmente, ne c'è questa opzione del "non chiudere" la versione che ho istallata è la 1.2.0

**Comment by raffybest94V01** [comment]
![immagine](https://cloud.githubusercontent.com/assets/15899684/22130364/d55567f0-deab-11e6-8291-c48503923ad9.png)

questo invece è il problema dei rettangoli bianchi io non capisco proprio quale sia il problema. preciso che prima del rilascio della versione 1.2.0 ( ora non mi ricordo quale versione avevo istallata ) l'aggiunta anime manuale funzionava.

**Comment by MyAnimeManager** [comment]
Prova ad aggiungere manualmente un fansub alla lista dei fansub, la trovi nel menù sotto la voce aggiungi, e poi riprova a fare l'aggiunta manuale. I quadrati bianchi sembrerebbero un problema di rendering, non è mai capitato a nessun'altra quindi non credo di poterci fare molto non potendolo riprodurre e capirne la causa. Potrebbe essere anche un problema del tuo PC, che non riesce a disegnare le finestre

**Comment by raffybest94V01** [comment]
incredibile ha funzionato il motivo allora era perché il campo era vuoto e quindi non lo aggiungeva ohh finalmente xD, comunque non penso sia un problema del mio pc visto che se lo fosse doveva farmelo anche con altri programmi ma sinceramente visto che succede solo a me mi basta riavviare e pace, ti ringrazio moltissimo per l'aiuto.

**Comment by MyAnimeManager** [comment]
Non so come mai fosse vuoto, teoricamente dovrebbe ogni volta generarlo con valori pre impostati. Per quanto riguarda inquadrati bianchi, ti giuro che non ho mai visto nulla di simile, è come se facesse fatica a far caricare a Java la skin del programma
