### ISSUE TITLE
Problema con aggiornamento 

### ISSUE THREAD

**Issue by raffybest94V01** [MyAnimeManager/MyAnimeManager#6]
successivamente all'aggiornamento di windows 10 alla creative non mi apre più il programma e mi genera questo errore, come posso risolvere ? 
[hs_err_pid14320.txt](https://github.com/MyAnimeManager/MyAnimeManager/files/914995/hs_err_pid14320.txt)

**Comment by raffybest94V01** [comment]
ok problema risolto, per chi ha problemi e causato dal programma "Riva Tunner" dovete chiuderlo o disinstallarlo, vedete che è collegato a MSI Afterburn quindi dovete chiudere anche quello.

**Comment by MyAnimeManager** [comment]
Comunque non è un problema legato a afterburner, solamente a reva tuner è un suo servizio. Ti conviene usare un programma diverso che faccia una cosa simile, in quanto quel programma va in conflitto con qualsiasi cosa usi Java a 64 bit

**Comment by raffybest94V01** [comment]
no infatti è un problema che è stato generato con l'update di windows 10 del creative update, precisamente la versione 1703.

**Comment by MyAnimeManager** [comment]
Da quel che ho trovato è problema del programma in particolare,  non dell'aggiornamento di Windows.
