### ISSUE TITLE
impossibile aggiungere nuovi anime

### ISSUE THREAD

**Issue by raffybest94V01** [MyAnimeManager/MyAnimeManager#7]
facendo click sull'icona "Aggiungi anime" se si prova a cercare anime usciti nel 2020 li trova, ma quando clicchiamo "Aggiungi" carica all'infinito e non lo aggiunge.

**Comment by MyAnimeManager** [comment]
Grazie per la segnalazione. Abbiamo già identificato il problema e provvederemo a rilasciare un aggiornamento a breve.
Saluti,

TEAM MyAnimeManager 

From: raffybest94V01 
Sent: Tuesday, January 7, 2020 1:21 AM
To: MyAnimeManager/MyAnimeManager 
Cc: Subscribed 
Subject: [MyAnimeManager/MyAnimeManager] impossibile aggiungere nuovi anime (#7)

facendo click sull'icona "Aggiungi anime" se si prova a cercare anime usciti nel 2020 li trova, ma quando clicchiamo "OK" carica all'infinito e non lo aggiunge.

**Comment by raffybest94V01** [comment]
confermo che con l'ultimo aggiornamento il problema è stato fixato, l'aggiornamento deve essere fatto scaricando il nuovo setup, l'update automatico una volta scaricato non aggiorna il programma.
